ComicApp/Models/Image.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicApp.Models
{
    public class Image
    {
        public string Path { get; set; }
        public string Extension { get; set; }
    }
}

ComicApp/Models/MarvelComic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicApp.Models
{
    public class MarvelComic
    {
        public int Id { get; set; }
        public int DigitalId { get; set; }
        public Image Thumbnail { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public double IssueNumber { get; set; }
    }
}

ComicApp/Models/MarvelComicSearchParam.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicApp.Models
{
    public class MarvelComicSearchParam
    {
        public string Format { get; set; }
        public string FormatType { get; set; }
        public string Title { get; set; }
        public string TitleStartsWith { get; set; }
        public int StartYear { get; set; }
        public int IssueNumber { get; set; }

    }
}

ComicApp/ViewModels/ComicViewModel.cs
using Comic.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicApp.ViewModels
{
    public class ComicViewModel
    {
        public string ResultsMsg;
        public List<ComicBook> Comics;
        public int SelectedComicId;
        public ComicBook SelectedComic;

        public ComicViewModel()
        {
            Comics = new List<ComicBook>();
            SelectedComic = new ComicBook();
        }
    }
}

ComicApp/ViewModels/MarvelViewModel.cs
using Comic.Data.Models;
using ComicApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicApp.ViewModels
{
    public class MarvelViewModel
    {
        public List<string> ComicFormatOptions { get; set; }
        public List<string> ComicFormatType { get; set; }
        public MarvelComicSearchParam ComicSearchParams { get; set; }
        public List<MarvelComic> MarvelComicsList { get; set; }

        public MarvelViewModel()
        {
            ComicFormatOptions = new List<string>()
            {
                "","comic","magazine","trade paperback", "hardcover", "digest", "graphic novel", "digital comic","infinite comic"
            };
            ComicFormatType = new List<string>()
            {
                "","comic", "collection"
            };
            ComicSearchParams = new MarvelComicSearchParam();
            MarvelComicsList = new List<MarvelComic>();
        }
    }
}

ComicApp/Controllers/ComicController.cs
using ComicApp.Services;
using Comic.Data.Models;
using ComicApp.ViewModels;
using System.Web.Mvc;
using System.Linq;


namespace ComicApp.Controllers
{
    public class ComicController : Controller
    {
        private ComicBook model = new ComicBook();
        private readonly IComicService _service;
        public ComicController(IComicService service)
        {
            _service = service;

        }
        #region Add Comic
        // GET: Comic
        [HttpGet]
        public ActionResult AddComic()
        {
            return View(model);
        }

        [HttpPost]
        public ActionResult AddComic(ComicBook comic)
        {
            //TODO: Add Server Validation before initiating Save
            //TODO: Add results Msg for Adding a New Comic
            string result = _service.AddNewComic(comic).Result;

            if(result != "ERROR")
            {
                model = new ComicBook();
            }
            else
            {
                model = comic;
            }
            return View(model);
        }
        #endregion Add Comic

        #region Update Comic

        [HttpGet]
        public ActionResult UpdateComic()
        {
            ComicViewModel cvm = new ComicViewModel();
            cvm.Comics = _service.GetAllComicBooks().Result.ToList();
            return View(cvm);
        }

        [HttpPost]
        public ActionResult UpdateComic(ComicBook SelectedComic)
        {
            ComicViewModel cvm = new ComicViewModel();
            cvm.SelectedComic = _service.UpdateComic(SelectedComic).Result;
            if(cvm.SelectedComic.Id > 0)
            {
                cvm.ResultsMsg = SelectedComic.Name + " has been successfully updated to " + cvm.SelectedComic.Name;
            }
            else
            {
               //ToDo:Error Handling
            }
            cvm.Comics = _service.GetAllComicBooks().Result.ToList();
            return View(cvm);
        }
        #endregion Update Comic

        #region Delete Comic
        [HttpGet]
        public ActionResult DeleteComic()
        {
            ComicViewModel cvm = new ComicViewModel();
            cvm.Comics = _service.GetAllComicBooks().Result.ToList();
            return View(cvm);
        }

        [HttpPost]
        public ActionResult DeleteComic(int SelectedComicId)
        {
            ComicViewModel cvm = new ComicViewModel();
            //ToDo:Validation
            //ToDo: Don't do look up just delete by id.

            if(SelectedComicId > 0)
            {
                ComicBook cb = new ComicBook();
                cb = _service.GetComicBookById(SelectedComicId).Result;
                string result = _service.RemoveComic(cb).Result;

                if(result == System.Net.HttpStatusCode.NoContent.ToString())
                {
                    cvm.ResultsMsg = cb.Name + " has been removed from your collection.";
                }
            }
            return View(cvm);
        }
        #endregion Delete Comic
    }
}

ComicApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ComicApp/Controllers/MarvelController.cs
using ComicApp.Services;
using ComicApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicApp.Controllers
{
    public class MarvelController : Controller
    {
        private MarvelViewModel _model = new MarvelViewModel();
        private IComicService _service;
        public MarvelController(IComicService service)
        {
            _service = service;
        }

        [HttpGet]
        public ActionResult SearchMarvel()
        {
            return View(_model);
        }

        [HttpPost]
        public ActionResult SearchMarvel(MarvelViewModel submission)
        {
            _model = submission;
            _model.MarvelComicsList = _service.SearchMarvel(submission.ComicSearchParams).Result.ToList();
            return View(_model);
        }

    }
}

ComicApp/Views/Comic/AddComic.cshtml
@model Comic.Data.Models.ComicBook
@{
    ViewBag.Title = "AddComic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Comic</h2>

@using (Html.BeginForm("AddComic", "Comic", FormMethod.Post, new { id = "addComic"}))
{
    <div class="form-group row">
        @Html.LabelFor(x => x.Name, new { @class="col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Name)
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(x => x.Description, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.Description)
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(x=>x.IssueNumber, new { @class="col-sm-2 col-form-label"})
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.IssueNumber, new { type = "number", step="any" })
        </div>
    </div>

    <input type="submit" value="submit" id="btnAdd" />
}

ComicApp/Views/Comic/DeleteComic.cshtml
@model ComicApp.ViewModels.ComicViewModel

@{
    ViewBag.Title = "DeleteComic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete Comic</h2>

@if(Model.ResultsMsg !="")
{
    <div class="text-success">@Model.ResultsMsg</div>
}

@using (Html.BeginForm("DeleteComic", "Comic", FormMethod.Post, new { id = "deleteComic" }))
{
    <div class="form-group row">
        <label class ="col-sm-2 col-form-label">Select a Comic Book:</label>
        <div class="col-sm-10">
            @Html.DropDownListFor(x=>x.SelectedComicId, new SelectList(Model.Comics,"Id","Name"),"Select a Comic", new { id="ddlComics"})
        </div>
    </div>
    <input type="submit" value="submit" id="btnDelete" />
}

ComicApp/Views/Comic/SearchCollection.cshtml
@{
    ViewBag.Title = "SearchCollection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SearchCollection</h2>

ComicApp/Views/Comic/SearchMarvel.cshtml
@{
    ViewBag.Title = "SearchMarvel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SearchMarvel</h2>

ComicApp/Views/Comic/UpdateComic.cshtml
@model ComicApp.ViewModels.ComicViewModel

@{
    ViewBag.Title = "UpdateComic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Update Comic</h2>

@using (Html.BeginForm("UpdateComic", "Comic", FormMethod.Post, new { id = "updateComic" }))
{
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Select a Comic Book:</label>
        <div class="col-sm-10">
            @Html.DropDownListFor(x => x.SelectedComicId, new SelectList(Model.Comics, "Id", "Name"), "--Select--", new { id = "ddlComics", onchange = "getComicDetails()" })
        </div>
    </div>
    @Html.HiddenFor(x=>x.SelectedComic.Id, new { id = "id" })
    <div class="form-group row">
        @Html.LabelFor(x => x.SelectedComic.Name, new { @class = "col-sm-2 col-form-label"})
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.SelectedComic.Name, new { id = "name" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(x => x.SelectedComic.Description, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.SelectedComic.Description, new { id="desc"})
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(x => x.SelectedComic.IssueNumber, new { @class = "col-sm-2 col-form-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(x => x.SelectedComic.IssueNumber, new { type = "number", step = "any", id ="issue" })
        </div>
    </div>
    <input type="submit" value="submit" id="btnUpdate" />
}

ComicApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ComicApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ComicApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>My Comic Collection</h1>
    <p class="lead">Add, Update, Delete and Search for Comic Books.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Browse Marvel Superheroes!</h2>
        <p>
            Look up your favorite marvel superheroes here.
        </p>
        <p><a class="btn btn-default" href="@Url.Action("SearchMarvel","Marvel")">Learn more &raquo;</a></p>
    </div>
</div>

ComicApp/Views/Marvel/SearchMarvel.cshtml
@model ComicApp.ViewModels.MarvelViewModel
@using ComicApp.Models
@{
    ViewBag.Title = "SearchMarvel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search Marvel Comics</h2>

<p>Fill out the search criteria below to look up Marvel Comics</p>

@using (Html.BeginForm("SearchMarvel", "Marvel", FormMethod.Post, new { id = "searchMarvel" }))
{
    <h5>Filters</h5>
    <div class="row">
        <div class="col-md-3">
            <label>Format:</label><br />
            @Html.DropDownListFor(x => x.ComicSearchParams.Format, new SelectList(Model.ComicFormatOptions), new { id = "formatOptions", @placeholder = "Format" })<br />
            <label>Format Type:</label><br />
            @Html.DropDownListFor(x => x.ComicSearchParams.FormatType, new SelectList(Model.ComicFormatType), new { id = "formatType", @placeholder = "Format Type" })
        </div>
        <div class="col-md-4">
            <label>Title:</label><br />
                @Html.TextBoxFor(x => x.ComicSearchParams.Title)<br />
            <label>Title Starts With:</label><br />
                @Html.TextBoxFor(x => x.ComicSearchParams.TitleStartsWith)
        </div>
        <div class="col-md-4">
            <label>Start Year:</label><br />
            @Html.TextBoxFor(x => x.ComicSearchParams.StartYear, new { type = "number", step = 1, @placeholder = "Start Year", value = "" })<br />
            <label>Issue Number:</label><br />
            @Html.TextBoxFor(x => x.ComicSearchParams.IssueNumber, new { type = "number", step = "any", @placeholder = "Issue Number", value = "" })
        </div>

        <input type="submit" value="Search" class="btn btn-default" />
    </div>
}

<div class="row">
    @{
        if (Model.MarvelComicsList != null)
        {
            foreach (MarvelComic comic in Model.MarvelComicsList)
            {
                <div class="col-md-6" style="min-height:150px;">
                    <div class="col-md-3">
                        @if (comic.Thumbnail.Path != "")
                        {
                            <img src="@string.Format("{0}.{1}",comic.Thumbnail.Path,comic.Thumbnail.Extension)" class="img-responsive thumbnail" />
                        }
                    </div>
                    <ul class="col-md-9">
                        <li>Title: @comic.Title</li>
                        <li>Issue Number: @comic.IssueNumber</li>
                        <li>Description: @comic.Description</li>
                    </ul>
                </div>
            }
        }
        else
        {
            <p>No results</p>
        }
    }
</div>

ComicApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker|Wendy+One" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Comic Collection", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Add Comic Book", "AddComic", "Comic")</li>
                    <li>@Html.ActionLink("Update Comic Book", "UpdateComic", "Comic")</li>
                    <li>@Html.ActionLink("Delete Comic Book", "DeleteComic", "Comic")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Comic Collection</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/chosen")
    @Scripts.Render("~/Scripts/comic.js")
    @RenderSection("scripts", required: false)
</body>
</html>